#page title
page_title                                : Houzez Mobile App                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.booleanbites.houzez                                          # Enter Google Play Store URL.
presskit_download_link                    : http://booleanbites.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Houzez Mobile App                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Android iOS app template for Houzez wordpress theme.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : BooleanBites
your_link                                 : http://booleanbites.com
your_city                                 : Pakistan                                
email_address                             : booleanbites.com
facebook_username                         : booleanbitesltd
instagram_username                        : 
twitter_username                          : booleanbites
github_username                           : AdilSoomro
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Made with Flutter
    description                           : This app has been developed in Flutter, its available on Android and iOS.
    fontawesome_icon_name                 : laptop-code

  - title                                 : Dynamic Home Screen
    description                           : Remotely customizable dynamic home screen with featured property, agent and agency carousel.
    fontawesome_icon_name                 : mobile

  - title                                 : Extensive Search and Filter
    description                           : All listing comes with advanced search and filter option.
    fontawesome_icon_name                 : search

  - title                                 : Light and Dark 
    description                           : It supports light and dark themes out of box.
    fontawesome_icon_name                 : palette

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, theme color, heading and text colors with few lines of code.
    fontawesome_icon_name                 : cogs

  - title                                 : Connect with user
    description                           : Bundled with all contact forms like contact agent, schedule Tour and inquire about property.
    fontawesome_icon_name                 : wpforms

  - title                                 : BLoC Pattern
    description                           : Independent code through BLoC pattern makes it easy to integrate with any API (other than Houzez).
    fontawesome_icon_name                 : puzzle-piece

  - title                                 : Enriched with property features
    description                           : Includes Google Maps, floor plans, 3D matterport, photo gallery, agent and agency profile.
    fontawesome_icon_name                 : magic

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#25ADDE"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
